SELECT 
	COUNT(*)
 FROM [ECOMMERCE_LIMPIO].[dbo].[ecomerce];
-- NULOS--
SELECT *
FROM [ECOMMERCE_LIMPIO].[dbo].[ecomerce]
WHERE
	ORDER_ID IS NULL OR ORDER_ID = ' ' OR
	ORDER_DATE IS NULL OR ORDER_DATE = ' ' OR
	AÑO IS NULL OR AÑO = ' ' OR
	MES IS NULL OR MES = ' ' OR
	CUSTOMER_NAME IS NULL OR CUSTOMER_NAME = ' ' OR
	CUSTOMER_SEGMENT IS NULL OR CUSTOMER_SEGMENT = ' ' OR
	COUNTRY IS NULL OR COUNTRY = ' ' OR
	REGION IS NULL OR REGION = ' ' OR
	PRODUCT_CATEGORY IS NULL OR PRODUCT_CATEGORY = ' ' OR
	PRODUCT_NAME IS NULL OR PRODUCT_NAME = ' ' OR
	QUANTITY IS NULL OR
	UNIT_PRICE IS NULL OR 
	DISCOUNT_PERCENT IS NULL OR 
	TOTAL_SALES IS NULL OR 
	Shipping_Cost IS NULL OR 
	Profit IS NULL OR 
	Payment_Method IS NULL OR Payment_Method = ' ' ;
-- ESPACIOS--
UPDATE [ECOMMERCE_LIMPIO].[dbo].[ecomerce]
SET 
    ORDER_ID = TRIM(ORDER_ID),
    CUSTOMER_NAME = TRIM(CUSTOMER_NAME),
    CUSTOMER_SEGMENT = TRIM(CUSTOMER_SEGMENT),
    COUNTRY = TRIM(COUNTRY),
    REGION = TRIM(REGION),
    PRODUCT_CATEGORY = TRIM(PRODUCT_CATEGORY),
    PRODUCT_NAME = TRIM(PRODUCT_NAME),
    PAYMENT_METHOD = TRIM(PAYMENT_METHOD);
--DUPLICADOS--
SELECT DISTINCT 
	ORDER_ID
FROM [ECOMMERCE_LIMPIO].[dbo].[ecomerce];
WITH Duplicados AS (
    SELECT *,
           ROW_NUMBER() OVER (
               PARTITION BY ORDER_ID, PRODUCT_NAME
               ORDER BY ORDER_DATE DESC
           ) AS fila
    FROM [ECOMMERCE_LIMPIO].[dbo].[ecomerce]
)
DELETE FROM Duplicados
WHERE fila > 1;
